-- RentBook root 접속
CREATE DATABASE rentBookDB;
USE rentBookDb;
CREATE TABLE tbl_books (
	B_CODE	VARCHAR(13)	NOT NULL	PRIMARY KEY,
	B_NAME	VARCHAR(125)	NOT NULL,	
	B_AUTHER	VARCHAR(125)	NOT NULL,	
	B_COMP	VARCHAR(125),		
	B_YEAR	INT	NOT NULL,	
	B_IPRICE	INT,		
	B_RPRICE	INT	NOT NULL	
);
DESC tbl_books;
DROP TABLE tbl_books;
SHOW TABLES;
DESC tbl_books;

